---
all:
  hosts:
  children:
    controller:
      hosts:
        ansible-1:
          ansible_host: 10.129.24.67
    servers:
      hosts:
        node1:
          ansible_host: 10.129.24.143
        node2:
          ansible_host: 10.129.24.68
        node3:
          ansible_host: 10.129.24.144
