---
- name: Playbook with Passwords
  # become: true
  hosts: controller
  vars:
    ssh_key_filename: id_rsa
  tasks:
    - name: "Check if id_rsa exists"
      ansible.builtin.stat:
        path: "~/.ssh/id_rsa"
      register: result
    - name: SSH keygen
      # requires pip install pexpect
      ansible.builtin.expect:
        command: ssh-keygen -t rsa
        responses:
          '(.*)Enter file in which to save the key(.*)': "\n"
          '(.*)passphrase(.*)': "\n"
      # creates lijkt niet te werken
      when: not result.stat.exists
      notify:
        - Copy_SSH_key
  handlers:
    - name: Copy_SSH_key
      ansible.builtin.expect:
        command: ssh-copy-id -i /home/student/.ssh/id_rsa.pub ubuntu@{{ item }}
        responses:
          '(.*)fingerprint(.*)': "yes\n"
          'password': "Azerty123\n"
      with_items: "{{ groups['servers'] | map('extract', hostvars, ['ansible_host']) }}"
      changed_when: true
